AWSTemplateFormatVersion: 2010-09-09
Description: Creates an SSE Queue with Cloud Watch alarms

Parameters:
  QueueName:
    Type: String
    Description: Enter the queue name. Note that FIFO queues must end with .fifo

  KmsMasterKeyId:
    Type: String
    Description: Enter the KMS master key ARN used for SSE
    AllowedPattern: ^.+$

  FifoQueueEnabled:
    Type: String
    Description: Enable queue FIFO characteristics
    Default: false
    AllowedValues:
      - true
      - false

  MessageRetentionPeriod:
    Type: Number
    Description: Enter the period in seconds that the message is retained
    MinValue: 60
    MaxValue: 345600
    Default: 86400

  AlarmTopicName:
    Type: String
    Description: Enter the queue name. Note that FIFO queues must end with .fifo

  QueueDepthAlarmThreshold:
    Type: Number
    Description: Enter the max queue depth threshold before a cloud watch alarm is triggered
    MinValue: 1
    MaxValue: 20000
    Default: 10

Conditions:
  UseFifoQueue: !Equals [!Ref FifoQueueEnabled, true]

Resources:
  SourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: !If [UseFifoQueue, true, !Ref "AWS::NoValue"]
      DelaySeconds: 0
      FifoQueue: !If [UseFifoQueue, true, !Ref "AWS::NoValue"]
      KmsMasterKeyId:
        Ref: KmsMasterKeyId
      KmsDataKeyReusePeriodSeconds: 300
      MessageRetentionPeriod:
        Ref: MessageRetentionPeriod
      MessageRetentionPeriod: 86400
      QueueName:
        Ref: QueueName
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 5

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: !If [UseFifoQueue, true, !Ref "AWS::NoValue"]
      MessageRetentionPeriod:
        Ref: MessageRetentionPeriod
      KmsMasterKeyId:
        Ref: KmsMasterKeyId


  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if queue depth grows beyond 3 messages
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        -
          Name: QueueName
          Value:
            Fn::GetAtt:
              - SourceQueue
              - QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold:
        Ref: QueueDepthAlarmThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        -
          Ref: AlarmTopic
      InsufficientDataActions:
        -
          Ref: AlarmTopic

  AlarmTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName:
        Ref: AlarmTopicName

Outputs:
  SourceQueueURL:
    Description: URL of the source queue
    Value:
      Ref: SourceQueue

  SourceQueueARN:
    Description: ARN of the source queue
    Value:
      Fn::GetAtt:
        - SourceQueue
        - Arn

  DeadLetterQueueURL:
    Description: URL of the dead letter queue
    Value:
      Ref: DeadLetterQueue

  DeadLetterQueueARN:
    Description: ARN of the dead letter queue
    Value:
      Fn::GetAtt:
        - DeadLetterQueue
        - Arn
