AWSTemplateFormatVersion: 2010-09-09
Description: Creates an SSE Queue with Cloud Watch alarms

Parameters:
  QueueName:
    Type: String
    Description: Enter the queue name. Note that FIFO queues must end with .fifo

  QueueWriteRoleArn:
    Type: String
    Description: Enter the ARN of the queue write role(s)

  KmsMasterKeyId:
    Type: String
    Description: Enter the KMS master key ARN used for SSE
    AllowedPattern: ^.+$

  FifoQueueEnabled:
    Type: String
    Description: Enable queue FIFO characteristics
    Default: false
    AllowedValues:
      - true
      - false

  MessageRetentionPeriod:
    Type: Number
    Description: Enter the period in seconds that the message is retained
    MinValue: 60
    MaxValue: 345600
    Default: 86400

  QueueDepthAlarmThreshold:
    Type: Number
    Description: Enter the max queue depth threshold before a cloud watch alarm is triggered
    MinValue: 1
    MaxValue: 20000
    Default: 10

Conditions:
  UseFifoQueue: !Equals [!Ref FifoQueueEnabled, true]

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: !If [UseFifoQueue, true, !Ref "AWS::NoValue"]
      DelaySeconds: 0
      FifoQueue: !If [UseFifoQueue, true, !Ref "AWS::NoValue"]
      KmsMasterKeyId:
        Ref: KmsMasterKeyId
      KmsDataKeyReusePeriodSeconds: 300
      MessageRetentionPeriod:
        Ref: MessageRetentionPeriod
      MessageRetentionPeriod: 86400
      QueueName:
        Ref: QueueName
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 5

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: !If [UseFifoQueue, true, !Ref "AWS::NoValue"]
      MessageRetentionPeriod:
        Ref: MessageRetentionPeriod
      KmsMasterKeyId:
        Ref: KmsMasterKeyId

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: QueuePolicy
        Statement:
          - Sid: QueueWriteAccess
            Effect: Allowed
            Principal:
              AWS:
              - Ref: QueueWriteRoleArn
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
            Resource:
              Fn::GetAtt:
                - Queue
                - Arn

  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if queue depth grows beyond 3 messages
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - Queue
              - QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold:
        Ref: QueueDepthAlarmThreshold
      ComparisonOperator: GreaterThanThreshold

Outputs:
  QueueURL:
    Description: URL of the source queue
    Value:
      Ref: Queue

  QueueARN:
    Description: ARN of the source queue
    Value:
      Fn::GetAtt:
        - Queue
        - Arn

  DeadLetterQueueURL:
    Description: URL of the dead letter queue
    Value:
      Ref: DeadLetterQueue

  DeadLetterQueueARN:
    Description: ARN of the dead letter queue
    Value:
      Fn::GetAtt:
        - DeadLetterQueue
        - Arn
